[2025-06-05T17:34:19.909+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-05T17:34:19.940+0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: push_autopark_import_pipeline.aggregate_import_data manual__2025-06-05T14:33:48.957618+00:00 [queued]>
[2025-06-05T17:34:19.950+0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: push_autopark_import_pipeline.aggregate_import_data manual__2025-06-05T14:33:48.957618+00:00 [queued]>
[2025-06-05T17:34:19.950+0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-05T17:34:19.966+0300] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): aggregate_import_data> on 2025-06-05 14:33:48.957618+00:00
[2025-06-05T17:34:19.969+0300] {standard_task_runner.py:72} INFO - Started process 20166 to run task
[2025-06-05T17:34:19.978+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'push_autopark_import_pipeline', 'aggregate_import_data', 'manual__2025-06-05T14:33:48.957618+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/push_autopark_import_pipeline.py', '--cfg-path', '/var/folders/p0/qnxbkr491pd245gy9gbyyml40000gn/T/tmp17ttes4i']
[2025-06-05T17:34:19.981+0300] {standard_task_runner.py:105} INFO - Job 9: Subtask aggregate_import_data
[2025-06-05T17:34:20.070+0300] {task_command.py:467} INFO - Running <TaskInstance: push_autopark_import_pipeline.aggregate_import_data manual__2025-06-05T14:33:48.957618+00:00 [running]> on host MacBook-Pro-Margarita.local
[2025-06-05T17:34:20.189+0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='push_autopark_import_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_import_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T14:33:48.957618+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T14:33:48.957618+00:00'
[2025-06-05T17:34:20.192+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-05T17:34:20.193+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-05T17:34:20.194+0300] {logging_mixin.py:190} INFO - Current task name:aggregate_import_data state:running start_date:2025-06-05 14:34:19.941325+00:00
[2025-06-05T17:34:20.194+0300] {logging_mixin.py:190} INFO - Dag name:push_autopark_import_pipeline and current dag run status:running
[2025-06-05T17:34:20.195+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-05T17:34:20.196+0300] {sql.py:278} INFO - Executing: CREATE TEMP TABLE import_aggregated AS
SELECT
    tecdocid,
    STRING_AGG(DISTINCT carid, ',' ORDER BY carid) AS carid,
    SUM(COALESCE(ap2023, 0)) AS ap2023,
    SUM(COALESCE(ap2024, 0)) AS ap2024,
    type
FROM import_prepare
GROUP BY tecdocid, type;
[2025-06-05T17:34:20.209+0300] {base.py:84} INFO - Retrieving connection 'postgres_car'
[2025-06-05T17:34:20.224+0300] {logging_mixin.py:190} WARNING - /Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py:30 RemovedInAirflow3Warning: This module is deprecated. Please use `airflow.providers.common.sql.hooks.sql`.
[2025-06-05T17:34:20.246+0300] {base.py:84} INFO - Retrieving connection 'postgres_car'
[2025-06-05T17:34:20.247+0300] {sql.py:218} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-airflow-providers-mysql<5.7.1
* apache-airflow-providers-elasticsearch<5.5.1
* apache-airflow-providers-postgres<5.13.0
[2025-06-05T17:34:20.254+0300] {sql.py:553} INFO - Running statement: CREATE TEMP TABLE import_aggregated AS
SELECT
    tecdocid,
    STRING_AGG(DISTINCT carid, ',' ORDER BY carid) AS carid,
    SUM(COALESCE(ap2023, 0)) AS ap2023,
    SUM(COALESCE(ap2024, 0)) AS ap2024,
    type
FROM import_prepare
GROUP BY tecdocid, type;, parameters: None
[2025-06-05T17:34:20.259+0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "import_prepare" does not exist
LINE 8: FROM import_prepare
             ^

[2025-06-05T17:34:20.300+0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-05T17:34:20.301+0300] {logging_mixin.py:190} INFO - Task start:2025-06-05 14:34:19.941325+00:00 end:2025-06-05 14:34:20.299820+00:00 duration:0.358495
[2025-06-05T17:34:20.302+0300] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): aggregate_import_data> dag:<DAG: push_autopark_import_pipeline> dagrun:<DagRun push_autopark_import_pipeline @ 2025-06-05 14:33:48.957618+00:00: manual__2025-06-05T14:33:48.957618+00:00, state:running, queued_at: 2025-06-05 14:33:49.010775+00:00. externally triggered: True>
[2025-06-05T17:34:20.303+0300] {logging_mixin.py:190} INFO - Failure caused by relation "import_prepare" does not exist
LINE 8: FROM import_prepare
             ^
[2025-06-05T17:34:20.304+0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=push_autopark_import_pipeline, task_id=aggregate_import_data, run_id=manual__2025-06-05T14:33:48.957618+00:00, execution_date=20250605T143348, start_date=20250605T143419, end_date=20250605T143420
[2025-06-05T17:34:20.325+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-05T17:34:20.326+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task aggregate_import_data (relation "import_prepare" does not exist
LINE 8: FROM import_prepare
             ^
; 20166)
Traceback (most recent call last):
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/Users/margaritaborodina/ALL_PROJECTS/airflow_car/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "import_prepare" does not exist
LINE 8: FROM import_prepare
             ^

[2025-06-05T17:34:20.374+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-05T17:34:20.435+0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-05T17:34:20.447+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
